---
- hosts: all
  become: true
  become_method: sudo

  pre_tasks:
    - user:
       name: science
       password: sfdmdr4MFuaoE

  roles:
    - role: geerlingguy.redis
      redis_bind_interface: 127.0.0.1

    - role: geerlingguy.nodejs
      nodejs_version: "0.12"
      nodejs_install_npm_user: "science"
      become: true
      become_method: sudo
