---
- hosts: all
  become: true
  become_method: sudo

  pre_tasks:
    - user:
       name: science
       password: sfdmdr4MFuaoE
       shell: /bin/bash

  roles:
    - role: geerlingguy.redis
      redis_bind_interface: 127.0.0.1

    - role: geerlingguy.nodejs
      nodejs_version: "0.12"
      nodejs_install_npm_user: "science"

    - role: geerlingguy.apache
      apache_listen_port_ssl: 443

  #...only JS would require git on a webserver
  # (ok, usually you build elsewhere... w/e)
  tasks:
    - name: Install git, because javascript
      package:
        name: "{{item}}"
        state: latest
      with_items:
          - git
          - node-gyp

    - name: Ensure hosting directory exists
      file:
        path: "{{item}}"
        owner: science
        group: science
        state: directory
        mode: 0755
      with_items:
        - /home/science/www
        - /home/science/www/logs
        - /home/science/www/node
        - /home/science/www/python

    - name: Bind synced folders to hosting directory
      mount:
        name: /home/science/www/{{item}}
        src: "{{item}}"
        fstype: vboxsf
        opts: uid=science,gid=science,rw
        state: mounted
      with_items:
        - python
        - node
